### ISSUE TITLE
Madness

### ISSUE THREAD

**Issue by DrFisura** [peteromallet/Steerable-Motion#2]
![image](https://github.com/peteromallet/ComfyUI-Creative-Interpolation/assets/113776225/3c00f82a-11d9-4d55-ba2e-096516938728)

There is absolutely nothing called frames_per_key_frame or cn_strength or soft_scaled_cn_weights_multiplier or interpolation or buffer anywhere.

Nowhere.

Forgive me I'm going crazy

**Comment by DrFisura** [comment]
README.md says:

"The main settings are:

    frames_per_key_frame: How many frames to generate between each main key frame you provide.
    length_of_key_frame_influence: How many frames to apply the ControlNet for after each key frame - the larger the number, the the wider range the input images will influence.
    cn_strength: How strong the control of the ControlNet should overall.
    buffer: the number of buffer frames places before your video - this is to prevent the end of the generation influencing the beginning due to how the context scheduler works"
    
    THIS DOESN'T EXIST
    
    ANYWHERE
    
    I'M GOING MAD

**Comment by DrFisura** [comment]
Now at the risk of being laughed at I'll reiterate: reality isn't real, and I'm doing everything wrong, whatever I do

**Comment by peteromallet** [comment]
Hi @DrFisura, so sorry for missing this, I never had gotten had Github issue. 

The problem is that the names don't appear in Comfy for text fields but they're the fields here: 

![CleanShot 2023-12-08 at 13 46 42](https://github.com/peteromallet/Steerable-Motion/assets/4647941/4d835f10-2bcb-4746-8f9c-7672f1c34b18)

The first big text field is frames_per_key_frame, the second is length_of_key_frame_influence, and 3rd is cn_strength.

Buffer should be down at the bottom. I'll update the documentation to make this more clear
